version: 2
jobs:
    test:
        docker:
            - image: circleci/node:8.9.3
        steps:
            - checkout
            - run: npm install
            - run: npm run test:coverage
            - run: npx codeclimate-test-reporter < ./coverage/lcov.info
            - run: npm test
workflows:
    version: 2
    test:
        jobs:
            - test
