version: 1

environment:
  the:
    post: 2

defaults:
  headers:
    hello: 'Hello2'

GET http://jsonplaceholder.typicode.com/posts/1:
  alias: a-post
  headers:
    hello: $jpa2:get-post.body.id


hosts:
  - host: jpa
    endpoint: http://jsonplaceholder.typicode.com
    GET /posts/$env.the.post: get-post
    GET /users/$jpa:get-post.body.userId: hello

  - host: jpa2
    endpoint: http://jsonplaceholder.typicode.com
    defaults:
      headers: false

    GET /posts/$jpa:get-post.body.id:
      alias: get-post



