version: 1
endpoint: http://httpbin.org

environment:
  the:
    post: 2

defaults:
  headers:
    hello: 'Hello2'

POST /anything:
  alias: anything
  payload:
    title: $jpa:get-post.body.title

---
host: jpa
endpoint: http://jsonplaceholder.typicode.com

GET /posts/$env.the.post: get-post
GET /users/$jpa:get-post.body.userId: hello
